// The bindings declared in wrangler.toml. Hand-written instead of generated by
// `wrangler types`, which emits a 15 000-line copy of the whole runtime typing.
interface RelayEnv {
  ROOM: DurableObjectNamespace;
  RATE: DurableObjectNamespace;
  /** The app's public Shikimori client id, a plain var in wrangler.toml. */
  SHIKIMORI_CLIENT_ID: string;
  /**
   * The client secret, set with `wrangler secret put SHIKIMORI_CLIENT_SECRET` and never written
   * down in this repository. It leaves the Worker only inside a request to Shikimori's own token
   * endpoint.
   *
   * Optional because a Worker deployed before the secret was put there really does have none, and
   * the token route has to answer that honestly rather than send Shikimori the word "undefined".
   */
  SHIKIMORI_CLIENT_SECRET?: string;
  /** A Kodik API token of our own, when there is one; otherwise the public one is scraped. */
  KODIK_TOKEN?: string;
}

declare namespace Cloudflare {
  // `cloudflare:test` and `cloudflare:workers` expose the environment under this name.
  interface Env extends RelayEnv {}
}

declare module "*?raw" {
  const text: string;
  export default text;
}
