// The bindings declared in wrangler.toml. Hand-written instead of generated by
// `wrangler types`, which emits a 15 000-line copy of the whole runtime typing.
interface RelayEnv {
  ROOM: DurableObjectNamespace;
}

declare namespace Cloudflare {
  // `cloudflare:test` and `cloudflare:workers` expose the environment under this name.
  interface Env extends RelayEnv {}
}
